### ISSUE TITLE
Открытие файла

### ISSUE THREAD

**Issue by Gotcha7770** [Gotcha7770/SystemExplorer#3]
Если пользователь выбрал файл в представлении и нажал Enter либо совершил двойной щелчок левой кнопкой мыши по файлу, это приводит к запуску нового процесса для открытия данного файла стандартными средствами, заданными в системе

**Comment by MarkPatka** [comment]
The presented implementation, possible won`t be relevant as a croos-platform, since its running  on System.Diagnostics.Process.dll
